### ISSUE TITLE
i2C problem with usb host shield

### ISSUE THREAD

**Issue by makerstorage** [wollewald/INA219_WE#2]
Hi,
I am using https://github.com/felis/USB_Host_Shield_2.0 lib to use an usb host shield to run a barcode device. It is SPI interface.
I am having trouble using the Wire.begin(); directive in order to init the i2c hardware with the USB host shield
commenting out the Wire.begin(); let my barcode scanner work but when I use Wire.begin(); in setup for arduino uno the reader did not work. The i2c device uses the A4 A5 pins on the board.

Did anybody have that problem before?

Regards,
Nuri Erginer

**Comment by wollewald** [comment]
Hi @makerstorage , 

sorry for the late response. Since I do not have this host shield it is difficult for me to solve this issue. Does it just not work or does it not compile? Are there any error messages you can share? Or have you found a solution meanwhile?

Regards, Wolfgang

**Comment by wollewald** [comment]
@makerstorage , since I received no answer to my question, I assume it's not relevant anymore.
