### ISSUE TITLE
Impossible to use together with ADS1115_WE

### ISSUE THREAD

**Issue by SovGVD** [wollewald/INA219_WE#6]
Hello. Thanks for amazing set of libraries.

I have a problem using INA219_WE together with ADS1115_WE:

```
/.../libraries/INA219_WE/src/INA219_WE.h:62:3: error: conflicting declaration 'typedef enum INA219_MEASURE_MODE measureMode'
 } measureMode;
   ^
/.../libraries/ADS1115_WE/src/ADS1115_WE.h:77:3: note: previous declaration as 'typedef enum ADS1115_MEASURE_MODE measureMode'
 } measureMode;
   ^
```

As you can see there is a conflict with names.

**Comment by wollewald** [comment]
@SovGVD First of all, thanks for the feedback!

Was easy to fix - please try.

**Comment by SovGVD** [comment]
Yay! Now it is compiling without issues. Thank you!
